#' Step1: compute MCA loading and embedding
#'
#' @param object A Seurat object.
#' @param nmcs Number of components to compute and store, default set to 50.
#' @param features Character vector of feature names. If not specified all features will be taken.
#' @param slot The slot to pull expression data for Seurat, default set to "data".
#'
#' @return Seurat object with MCA calculation stored in the reductions slot.
#' @export
#'
#' @examples
computeMCA <- function(object, nmcs = 50, features = NULL, slot = "data") {
  object <- NormalizeData(object)
  object <- RunMCA(object, nmcs = nmcs, features = features, slot = slot)
  return(object)
}


#' Step2: Get gene occurrence rate in background and pathway genesets
#'
#' @param background.file Background genesets file, in GMT format.
#' @param pathway.geneset Pathway geneset, a R object of list which include tags (pathway name) and values (gene list).
#'
#' @return A data frame include background and pathways gene rate.
#' @export
#'
#' @examples
getGeneRate <- function(background.file = NULL, pathway.geneset = NULL) {
  # get background genesets
  if (!file.exists(background.file)) {
    stop(paste0("Cannot find file: ", background.file))
  }
  background_genesets <- readGMT(background.file)

  # get signature geneset
  if (class(pathway.geneset) != "list") {
    pathway_geneset <- list(pathway.geneset)
  } else {
    pathway_geneset <- pathway.geneset
  }
  if (is.null(names(pathway_geneset))) {
    names(pathway_geneset) <- paste0("pathway", 1:length(pathway_geneset))
  }

  # merge background and signature genesets
  all_genesets <- c(background_genesets, pathway_geneset)

  # get all unique genes from all genesets
  all_gene <- unique(unlist(all_genesets, use.names = FALSE))
  geneset_names <- names(all_genesets)

  # build geneset-gene matrix, row is gene name, col is geneset name
  # Value is whether this gene exist in this geneset, 1-exist 0-noexist
  geneset_gene_matrix <- matrix(0, nrow = length(all_gene), ncol = length(geneset_names),
                                dimnames = list(all_gene, geneset_names))
  for (name in geneset_names) {
    current_list <- all_genesets[[name]]
    for (value in all_gene) {
      if (value %in% current_list) {
        geneset_gene_matrix[value == all_gene, name == geneset_names] <- 1
      }
    }
  }
  background_genesets_df <- data.frame(geneset_gene_matrix)
  pathway.name <- tail(colnames(background_genesets_df), length(pathway.geneset))

  # calculate the gene occurrence rate in background and pathway genesets
  background_rate <- rowMeans(background_genesets_df)
  signature_rate <- background_genesets_df[, pathway.name]

  gene_rate <- data.frame(background_rate, signature_rate)
  names(gene_rate) <- c("background", pathway.name)

  return (gene_rate)
}


readGMT = function(gmt_file_path, n_gene_thre = 0){
  paths = readLines(gmt_file_path)
  genesets = list()
  for(i in 1:length(paths)){
    t = strsplit(paths[i],'\t')[[1]]
    genes = t[3:length(t)]
    genes = genes[which(genes != "")]
    genes = unique(genes)
    genesets[[t[1]]] = genes
  }
  return (genesets)
}


#' Step3: Do regression of gene loading (Y) and gene rate (X)
#'
#' @param object A Seurat object include MCA data in reductions slot.
#' @param gene.rate Gene rate data frame, generated by getGeneRate.
#'
#' @return A data frame include t and p value of pathways and corresponding background, dim=(4*num(pathways), nmcs).
#' @export
#'
#' @examples
doRegression <- function(object, gene.rate = NULL) {
  # get common gene of features and all genes
  common_gene <- intersect(rownames(gene.rate), rownames(object@reductions$mca@feature.loadings))

  # filter gene of gene rate and loading data
  gene_rate <- gene.rate[common_gene, ]
  mca_loading <- object@reductions$mca@feature.loadings[common_gene, ]

  # do regression by every MCA dimension
  use_pathway_name <- tail(colnames(gene_rate), ncol(gene_rate) - 1)
  t_rowname <- paste(use_pathway_name, "t", sep = ".")
  background_t_rowname <- paste(use_pathway_name, "background.t", sep = ".")
  p_rowname <- paste(use_pathway_name, "pvalue", sep = ".")
  background_p_rowname <- paste(use_pathway_name, "background.pvalue", sep = ".")
  rowNames = c(t_rowname, background_t_rowname, p_rowname, background_p_rowname)
  regression_result <- matrix(0, nrow = 4 * (ncol(gene_rate) - 1), ncol = ncol(mca_loading),
                              dimnames = list(rowNames, colnames(mca_loading)))
  for (pathway_name in use_pathway_name) {
    for (dim_name in colnames(mca_loading)) {
      # construce data and formula to regression
      mca_loading_dim <- mca_loading[, dim_name]
      gene_rate_pathway <- gene_rate[, c("background", pathway_name)]
      lm_data <- data.frame(gene_rate_pathway, mca_loading_dim)
      names(lm_data) <- c(names(gene_rate_pathway), dim_name)
      formula <- paste(dim_name, "~", paste(names(gene_rate_pathway), collapse = " + "))

      lm <- lm(formula, data = lm_data)

      background_t_value <- summary(lm)$coefficients["background", 3]
      background_p_value <- summary(lm)$coefficients["background", 4]
      t_value <- summary(lm)$coefficients[pathway_name, 3]
      p_value <- summary(lm)$coefficients[pathway_name, 4]

      regression_result[paste(pathway_name, "background.t", sep = "."), dim_name] <- background_t_value
      regression_result[paste(pathway_name, "background.pvalue", sep = "."), dim_name] <- background_p_value
      regression_result[paste(pathway_name, "t", sep = "."), dim_name] <- t_value
      regression_result[paste(pathway_name, "pvalue", sep = "."), dim_name] <- p_value
    }
  }

  # order by pathway name
  row_order <- order(rownames(regression_result))
  regression_result <- regression_result[row_order, ]
  return(regression_result)
}


#' Step4: Compute the pathway activity score.
#'
#' @param object A Seurat object include MCA data in reductions slot.
#' @param regression.data Regression data frame, generated by doRegression.
#' @param pvalue The cutoff p value of linear regression result.
#' @param weight Whether calculate the weighted activity score, weighted means that the variance contribution rate of MCA reduction is used as the weight of each dimension.
#' @param normalize Normalize flag, 0:Not normalized, 1:Z-Score normalized, 2-Background activity score normalized, default 1.
#'
#' @return A data frame store cell pathways activity score.
#' @export
#'
#' @examples
computeScore <- function(object, regression.data = NULL, pvalue = 0.05, weight = FALSE, normalize = 1) {
  mca_embedding <- object@reductions$mca@cell.embeddings
  regression_data <- regression.data[!grepl("background", rownames(regression.data)), ]
  pvalue_rowname <- rownames(regression_data)[grepl(".pvalue", rownames(regression_data))]
  score_name_list <- sub(".pvalue", "", pvalue_rowname)
  score_data <- matrix(0, nrow = nrow(mca_embedding), ncol = length(score_name_list),
                       dimnames = list(rownames(mca_embedding), score_name_list))
  if (normalize == 2) {
    background_regression_data <- regression.data[grepl("background", rownames(regression.data)), ]
    background_pvalue_rowname <- rownames(background_regression_data)[grepl(".pvalue", rownames(background_regression_data))]
    background_score_name_list <- sub(".pvalue", "", background_pvalue_rowname)
    background_score_data <- matrix(0, nrow = nrow(mca_embedding), ncol = length(background_score_name_list),
                                    dimnames = list(rownames(mca_embedding), background_score_name_list))
  }

  for (pathway_name in score_name_list) {
    # filter the regression data
    pathway_pvalue_name <- paste0(pathway_name, '.pvalue')
    use_dims_flag <- regression_data[pathway_pvalue_name, ] < pvalue
    if (sum(use_dims_flag) == 0) {
      message(paste(pathway_name, "don't have dimensions that p-value satisfied, all dimensions are used."))
      use_dims_flag <- !use_dims_flag
    }
    use_dims <- colnames(regression_data)[use_dims_flag]

    # calculate the pathway activity score
    stdev <- object@reductions$mca@stdev
    use_embedding = as.matrix(mca_embedding[, use_dims])
    use_t_name <- paste0(pathway_name, '.t')
    use_regression_data = regression_data[use_t_name, use_dims]
    use_stdev <- stdev[use_dims_flag]
    for(i in 1:length(use_regression_data)) {
      use_embedding[, i] = use_embedding[, i] * use_regression_data[i]
      if (weight) {
        use_embedding[, i] = use_embedding[, i] * use_stdev[i] / sum(use_stdev) * length(use_stdev)
      }
    }
    activity_score = apply(use_embedding, 1, sum) / sum(abs(use_regression_data))

    if (normalize == 1) { # Z-score normalize
      activity_score <- (activity_score - mean(activity_score)) / sd(activity_score)
    }
    if (normalize == 2) { # normalize by background activity score
      use_background_t_name <- paste0(pathway_name, '.background.t')
      use_background_dims <- use_dims
      use_background_regression_data = background_regression_data[use_background_t_name, use_background_dims]
      use_background_embedding = as.matrix(mca_embedding[, use_background_dims])
      for(i in 1:length(use_background_regression_data)) {
        use_background_embedding[, i] = use_background_embedding[, i] * use_background_regression_data[i]
        if (weight) {
          use_background_embedding[, i] = use_background_embedding[, i] * use_stdev[i] / sum(use_stdev) * length(use_stdev)
        }
      }
      background_activity_score = apply(use_background_embedding, 1, sum) / sum(abs(use_background_regression_data))
      activity_score <- (activity_score - mean(background_activity_score)) / sd(background_activity_score)
    }

    score_data[, pathway_name] <- activity_score
  }

  return(data.frame(score_data))
}


#' Title Binarization the pathway activity score by Kmeans cluster.
#'
#' @param score.data A data frame store cell pathway activity score in column 1.
#' @param n.cluster Number of clusters, 2 or 3 is recommended, default set to 2.
#'
#' @return A data frame store the binarization label.
#' @export
#'
#' @examples
doBinarization <- function(score.data, n.cluster = 2) {
  label_data <- score.data
  colnames(label_data) <- gsub("score", "label", colnames(score.data))
  for (pathway_score_name in colnames(label_data)) {
    pathway_score_data <- label_data[pathway_score_name]
    kmeans_result <- kmeans(pathway_score_data, centers = n.cluster)
    centers <- kmeans_result$centers
    threshold <- (centers[n.cluster] + centers[n.cluster - 1]) / 2
    label_data[pathway_score_name] <- ifelse(pathway_score_data > threshold, "positive", "negative")
  }

  return(label_data)
}




