
#' Compute MCA loading and embedding
#'
#' @param object A Seurat object.
#' @param nmcs Number of components to compute and store, default set to 20.
#' @param features Character vector of feature names. If not specified all features will be taken.
#' @param slot The slot to pull expression data for Seurat, default set to "data".
#' @param assay Name of Assay MCA is being run on, default set to "RNA".

#'
#' @return Seurat object with MCA calculation stored in the reductions slot.
#' @export
#'
#' @examples
computeMCA <- function(object, nmcs = 20, features = NULL, slot = "data", assay = "RNA") {
  object <- NormalizeData(object)
  object <- RunMCA(object, nmcs = nmcs, features = features, slot = slot, assay = assay)
  return(object)
}


#' Get gene occurrence rate in background and pathway genesets
#'
#' @param background.geneset Background genesets file name (in GMT format) or R list object.
#' @param pathway.geneset Pathway geneset, a R object of list which include tags (pathway name) and values (gene list).
#'
#' @return A data frame include background and pathways gene rate.
#' @export
#'
#' @examples
getGeneRate <- function(background.geneset = NULL, pathway.geneset = NULL) {
  # get background genesets
  if (class(background.geneset) == "list") {
    background_genesets <- background.geneset
  } else {
    if (!file.exists(background.geneset)) {
      stop(paste0("Cannot find file: ", background.geneset))
    }
    background_genesets <- readGMT(background.geneset)
  }

  # get pathway geneset
  if (class(pathway.geneset) != "list") {
    pathway_geneset <- list(pathway.geneset)
  } else {
    pathway_geneset <- pathway.geneset
  }
  if (is.null(names(pathway_geneset))) {
    names(pathway_geneset) <- paste0("pathway", 1:length(pathway_geneset))
  }

  # merge background and signature genesets
  all_genesets <- removeDuplicates(c(background_genesets, pathway_geneset))

  # get all unique genes from all genesets
  all_gene <- unique(unlist(all_genesets, use.names = FALSE))
  geneset_names <- names(all_genesets)
  # build geneset-gene matrix, row is gene name, col is geneset name
  # Value is whether this gene exist in this geneset, 1-exist 0-noexist
  geneset_gene_matrix <- matrix(0, nrow = length(all_gene), ncol = length(geneset_names),
                                dimnames = list(all_gene, geneset_names))
  for (name in geneset_names) {
    current_list <- all_genesets[[name]]
    for (value in all_gene) {
      if (value %in% current_list) {
        geneset_gene_matrix[value == all_gene, name == geneset_names] <- 1
      }
    }
  }
  background_genesets_df <- data.frame(geneset_gene_matrix)

  # calculate the gene occurrence rate in background and pathway genesets
  background_rate <- rowMeans(background_genesets_df)
  pathway_rate <- background_genesets_df[, names(pathway_geneset)]

  gene_rate <- data.frame(background_rate, pathway_rate)
  names(gene_rate) <- c("background", names(pathway_geneset))

  return (gene_rate)
}


readGMT = function(gmt_file_path, n_gene_thre = 0){
  paths = readLines(gmt_file_path)
  genesets = list()
  for(i in 1:length(paths)){
    t = strsplit(paths[i],'\t')[[1]]
    genes = t[3:length(t)]
    genes = genes[which(genes != "")]
    genes = unique(genes)
    genesets[[t[1]]] = genes
  }
  return (genesets)
}

removeDuplicates <- function(lst) {
  unique_lst <- list()
  for (name in names(lst)) {
    if (!(name %in% names(unique_lst))) {
      unique_lst[[name]] <- lst[[name]]
    }
  }
  return(unique_lst)
}


#' Do regression of gene loading (Y) and gene rate (X)
#'
#' @param object A Seurat object include MCA data in reductions slot.
#' @param gene.rate Gene rate data frame, generated by getGeneRate.
#'
#' @return A data frame include t and p value of pathways and corresponding background, dim=(4*num(pathways), nmcs).
#' @export
#'
#' @examples
doRegression <- function(object, gene.rate = NULL) {
  # get common gene of features and all genes
  common_gene <- intersect(rownames(gene.rate), rownames(object@reductions$mca@feature.loadings))

  # filter gene of gene rate and loading data
  gene_rate <- gene.rate[common_gene, ]
  mca_loading <- object@reductions$mca@feature.loadings[common_gene, ]

  # do regression by every MCA dimension
  use_pathway_name <- tail(colnames(gene_rate), ncol(gene_rate) - 1)
  t_rowname <- paste(use_pathway_name, "t", sep = ".")
  background_t_rowname <- paste(use_pathway_name, "background.t", sep = ".")
  p_rowname <- paste(use_pathway_name, "pvalue", sep = ".")
  background_p_rowname <- paste(use_pathway_name, "background.pvalue", sep = ".")
  rowNames = c(t_rowname, background_t_rowname, p_rowname, background_p_rowname)
  regression_result <- matrix(0, nrow = 4 * (ncol(gene_rate) - 1), ncol = ncol(mca_loading),
                              dimnames = list(rowNames, colnames(mca_loading)))
  for (pathway_name in use_pathway_name) {
    gene_rate_pathway <- gene_rate[, pathway_name]
    if (sum(gene_rate_pathway) == 0) { # no genes in pathway, assign to NA
      regression_result[paste(pathway_name, "background.t", sep = "."), ] <- NA
      regression_result[paste(pathway_name, "background.pvalue", sep = "."), ] <- NA
      regression_result[paste(pathway_name, "t", sep = "."), ] <- NA
      regression_result[paste(pathway_name, "pvalue", sep = "."), ] <- NA
    } else {
      for (dim_name in colnames(mca_loading)) {
        # construce data and formula to regression
        mca_loading_dim <- mca_loading[, dim_name]

        gene_rate_merge <- gene_rate[, c("background", pathway_name)]
        lm_data <- data.frame(gene_rate_merge, mca_loading_dim)
        names(lm_data) <- c(names(gene_rate_merge), dim_name)
        formula <- paste(dim_name, "~", paste(names(gene_rate_merge), collapse = " + "))

        lm <- lm(formula, data = lm_data)

        background_t_value <- summary(lm)$coefficients["background", 3]
        background_p_value <- summary(lm)$coefficients["background", 4]
        t_value <- summary(lm)$coefficients[pathway_name, 3]
        p_value <- summary(lm)$coefficients[pathway_name, 4]

        regression_result[paste(pathway_name, "background.t", sep = "."), dim_name] <- background_t_value
        regression_result[paste(pathway_name, "background.pvalue", sep = "."), dim_name] <- background_p_value
        regression_result[paste(pathway_name, "t", sep = "."), dim_name] <- t_value
        regression_result[paste(pathway_name, "pvalue", sep = "."), dim_name] <- p_value
      }
    }
  }

  # order by pathway name
  # row_order <- order(rownames(regression_result))
  # regression_result <- regression_result[row_order, ]
  return(regression_result)
}


#' Compute the pathway activity score.
#'
#' @param object A Seurat object include MCA data in reductions slot.
#' @param regression.data Regression data frame, generated by doRegression.
#' @param pvalue The cutoff p value of linear regression result, default set to 0.05.
#' @param weight Whether calculate the weighted activity score, weighted means that the variance contribution rate of MCA reduction is used as the weight of each dimension. Default set to FALSE.
#' @param normalize Normalize method, The choices are NULL, "z-score" and "bg-score". "z-socre" means z-score normalize, "bg-score" means normalize by background activity score. Default set to "z-score".
#'
#' @return A data frame store single-cell pathways activity score.
#' @export
#'
#' @examples
computeScore <- function(object, regression.data = NULL, pvalue = 0.05, weight = FALSE, normalize = "z-score") {
  mca_embedding <- object@reductions$mca@cell.embeddings
  regression_data <- regression.data[!grepl("background", rownames(regression.data)), ]
  pvalue_rowname <- rownames(regression_data)[grepl(".pvalue", rownames(regression_data))]
  score_name_list <- sub(".pvalue", "", pvalue_rowname)
  score_data <- matrix(0, nrow = nrow(mca_embedding), ncol = length(score_name_list),
                       dimnames = list(rownames(mca_embedding), score_name_list))
  if (!is.null(normalize) & normalize == "bg-score") {
    background_regression_data <- regression.data[grepl("background", rownames(regression.data)), ]
    background_pvalue_rowname <- rownames(background_regression_data)[grepl(".pvalue", rownames(background_regression_data))]
    background_score_name_list <- sub(".pvalue", "", background_pvalue_rowname)
    background_score_data <- matrix(0, nrow = nrow(mca_embedding), ncol = length(background_score_name_list),
                                    dimnames = list(rownames(mca_embedding), background_score_name_list))
  }

  for (pathway_name in score_name_list) {
    # filter the regression data
    pathway_pvalue_name <- paste0(pathway_name, '.pvalue')
    regression_data_pathway_pvalue = regression_data[pathway_pvalue_name, ]
    if(all(is.na(regression_data_pathway_pvalue))) { # no valid value exists
      score_data[, pathway_name] <- NA
    } else {
      use_dims_flag <- regression_data_pathway_pvalue < pvalue
      if (sum(use_dims_flag) == 0) {
        # message(paste(pathway_name, "don't have dimensions that p-value satisfied, all dimensions are used."))
        use_dims_flag <- !use_dims_flag
      }
      use_dims <- colnames(regression_data)[use_dims_flag]

      # calculate the pathway activity score
      stdev <- object@reductions$mca@stdev
      use_embedding = as.matrix(mca_embedding[, use_dims])
      use_t_name <- paste0(pathway_name, '.t')
      use_regression_data = regression_data[use_t_name, use_dims]
      use_stdev <- stdev[use_dims_flag]
      for(i in 1:length(use_regression_data)) {
        use_embedding[, i] = use_embedding[, i] * use_regression_data[i]
        if (weight) {
          use_embedding[, i] = use_embedding[, i] * use_stdev[i] / sum(use_stdev) * length(use_stdev)
        }
      }
      activity_score = apply(use_embedding, 1, sum) / sum(abs(use_regression_data))

      if (!is.null(normalize) & normalize == "z-score") { # Z-score normalize
        activity_score <- (activity_score - mean(activity_score)) / sd(activity_score)
      }
      if (!is.null(normalize) & normalize == "bg-score") { # normalize by background activity score
        use_background_t_name <- paste0(pathway_name, '.background.t')
        use_background_dims <- use_dims
        use_background_regression_data = background_regression_data[use_background_t_name, use_background_dims]
        use_background_embedding = as.matrix(mca_embedding[, use_background_dims])
        for(i in 1:length(use_background_regression_data)) {
          use_background_embedding[, i] = use_background_embedding[, i] * use_background_regression_data[i]
          if (weight) {
            use_background_embedding[, i] = use_background_embedding[, i] * use_stdev[i] / sum(use_stdev) * length(use_stdev)
          }
        }
        background_activity_score = apply(use_background_embedding, 1, sum) / sum(abs(use_background_regression_data))
        activity_score <- (activity_score - mean(background_activity_score)) / sd(background_activity_score)
      }

      score_data[, pathway_name] <- activity_score
    }

  }

  return(data.frame(score_data))
}


#' Title Binarization the pathway activity score by Kmeans cluster.
#'
#' @param score.data A data frame store cell pathway activity score in column 1.
#' @param n.cluster Number of clusters, 2 or 3 is recommended, default set to 2.
#' @param method Binarization method, The choices are "GMM", "kmeans", default set to "GMM". "GMM" is Gaussian Mixture Model, "kmeans" is K-means cluster.
#'
#' @return A data frame store the binarization label.
#' @export
#'
#' @examples
doBinarization <- function(score.data, n.cluster = 2, method = "GMM") {
  label_data <- score.data
  colnames(label_data) <- paste0(colnames(score.data), ".label")
  for (pathway_score_name in colnames(label_data)) {
    pathway_score_data <- label_data[pathway_score_name]
    if (method == "GMM") {
      fit <- normalmixEM(pathway_score_data[[1]], k = n.cluster, maxit = 1000, eps = 1e-5)
      mean1 <- fit$mu[n.cluster - 1]
      mean2 <- fit$mu[n.cluster]
      threshold <- (mean1 + mean2) / 2
    }
    if (method == "kmeans") {
      kmeans_result <- kmeans(pathway_score_data, centers = n.cluster)
      center1 <- kmeans_result$centers[n.cluster - 1]
      center2 <- kmeans_result$centers[n.cluster]
      threshold <- (center1 + center2) / 2
    }

    label_data[, pathway_score_name] <- ifelse(pathway_score_data > threshold, "positive", "negative")
  }

  return(label_data)
}


#' Calculate mutual information.
#'
#' @param x A random variable (vector/factor).
#' @param y Another random variable (vector/factor), or dataframe which each columns is a random variable.
#' @param num_bins The number of intervals into which random variable is to be cut, default set to 20.
#' @param num_permutations Number of permutations to use, if greater than 0, compute empirical p-values using a permutation test. Default set to 100.
#'
#' @return A data frame store mutual information, and pvalue if num_permutations > 0.
#' @export
#'
#' @examples
calculateMI <- function(x, y, num_bins = 20, num_permutations = 100) {
  if (class(y) != "data.frame") {
    y <- data.frame(y)
  }

  if (length(x_bins) != nrow(y)) {
    stop("x and y must have the same length")
  }

  message("Calculate mutual information...")
  result <- matrix(0, nrow = ncol(y), ncol = 2, dimnames = list(names(y), c("MI", "pvalue")))
  for (col in names(y)) {
    # Create bins
    x_bins <- cut(x, breaks = num_bins, labels = FALSE)
    y_bins <- cut(y[[col]], breaks = num_bins, labels = FALSE)

    # Calculate mutual information
    mi <- compute.2d.MI(x_bins, y_bins)
    result[col, "MI"] <- mi
  }

  message("Do permutations...")
  if (num_permutations > 0) {
    # Do permutations
    permuted_mi_list <- numeric(num_permutations)
    y_vector <- as.vector(unlist(y))
    for(n in 1:num_permutations) {
      permuted_y <- sample(y_vector, nrow(y))
      permuted_y_bins <- cut(permuted_y, breaks = num_bins, labels = FALSE)
      permuted_mi <- compute.2d.MI(x_bins, permuted_y_bins)
      permuted_mi_list[n] <- permuted_mi
    }

    mean_val <- mean(permuted_mi_list)
    sd_val <- sd(permuted_mi_list)
    for (row in rownames(result)) {
      mi <- result[row, "MI"]

      # Calculate p-value
      p_value <- pnorm(mi, mean = mean_val, sd = sd_val, lower.tail = FALSE)
      result[row, "pvalue"] <- p_value
    }
  } else {
    result[, "pvalue"] <- NA
  }

  result_df <- data.frame(result)
  return(result_df)
}

compute.2d.MI <- function(x_bins, y_bins) {
  # Calculate marginal probabilities and joint probabilities
  joint_freq <- table(x_bins, y_bins)
  p_x <- rowSums(joint_freq) / sum(joint_freq)
  p_y <- colSums(joint_freq) / sum(joint_freq)
  p_xy <- joint_freq / sum(joint_freq)

  # Calculate mutual information
  mi <- 0
  for (i in 1:nrow(p_xy)) {
    for (j in 1:ncol(p_xy)) {
      if (p_xy[i,j] > 0) {
        mi <- mi + p_xy[i,j] * log(p_xy[i,j] / (p_x[i] * p_y[j]))
      }
    }
  }

  return(as.numeric(mi))
}


#'Calculate spatial mutual information (z to x,y).
#'
#' @param x A random variable (vector/factor) on the first axis.
#' @param y A random variable (vector/factor) on the second axis.
#' @param z The random variable (vector/factor) or dataframe (each columns is a random variable) to be calculate spatial mutual information to x and y.
#' @param num_bins The number of intervals into which x, y and z is to be cut, default set to 20.
#' @param num_permutations Number of permutations to use, if greater than 0, compute empirical p-values using a permutation test. Default set to 100.
#'
#' @return A data frame store spatial mutual information, and pvalue if num_permutations > 0.
#' @export
#'
#' @examples
calculateSpatialMI <- function(x, y, z, num_bins = 20, num_permutations = 100) {
  if (class(z) != "data.frame") {
    z <- data.frame(z)
  }

  # Input validation
  if (length(x) != length(y) || length(x) != nrow(z)) {
    stop("x, y, and z must have the same length")
  }

  message("Calculate spatial mutual information...")
  result <- matrix(0, nrow = ncol(z), ncol = 2, dimnames = list(names(z), c("MI", "pvalue")))
  for (col in names(z)) {
    # Create bins
    x_bins <- cut(x, breaks = num_bins, labels = FALSE)
    y_bins <- cut(y, breaks = num_bins, labels = FALSE)
    z_bins <- cut(z[[col]], breaks = num_bins, labels = FALSE)

    # Calculate mutual information
    mi <- compute.3d.MI(x_bins, y_bins, z_bins)
    result[col, "MI"] <- mi
  }

  if (num_permutations > 0) {
    message("Do permutations...")
    # Do permutations
    permuted_mi_list <- numeric(num_permutations)
    z_vector <- as.vector(unlist(z))
    for(n in 1:num_permutations) {
      permuted_z <- sample(z_vector, nrow(z))
      permuted_z_bins <- cut(permuted_z, breaks = num_bins, labels = FALSE)
      permuted_mi <- compute.3d.MI(x_bins, y_bins, permuted_z_bins)
      permuted_mi_list[n] <- permuted_mi
    }

    mean_val <- mean(permuted_mi_list)
    sd_val <- sd(permuted_mi_list)
    for (row in rownames(result)) {
      mi <- result[row, "MI"]

      # Calculate p-value
      p_value <- pnorm(mi, mean = mean_val, sd = sd_val, lower.tail = FALSE)
      result[row, "pvalue"] <- p_value
    }
  } else {
    result[, "pvalue"] <- NA
  }

  result_df <- data.frame(result)
  return(result_df)
}

compute.3d.MI <- function(x_bins, y_bins, z_bins) {
  # Calculate joint frequencies for spatial location and z
  xy_bins <- paste(x_bins, y_bins, sep = "_")
  joint_freq <- table(xy_bins, z_bins)

  # Calculate marginal probabilities and joint probabilities
  p_xy <- rowSums(joint_freq) / sum(joint_freq)
  p_z <- colSums(joint_freq) / sum(joint_freq)
  p_xyz <- joint_freq / sum(joint_freq)

  # Calculate mutual information
  mi <- 0
  for (i in 1:nrow(p_xyz)) {
    for (j in 1:ncol(p_xyz)) {
      if (p_xyz[i,j] > 0) {
        mi <- mi + p_xyz[i,j] * log(p_xyz[i,j] / (p_xy[i] * p_z[j]))
      }
    }
  }

  return(as.numeric(mi))
}

