#' Step1: compute MCA loading and embedding
#'
#' @param object A Seurat object.
#' @param nmcs Number of components to compute and store, default set to 50.
#' @param features Character vector of feature names. If not specified all features will be taken.
#' @param slot The slot to pull expression data for Seurat, default set to "data".
#'
#' @return Seurat object with MCA calculation stored in the reductions slot.
#' @export
#'
#' @examples
computeMCA <- function(object, nmcs = 50, features = NULL, slot = "data") {
  use.features <- intersect(features, rownames(object))
  object <- NormalizeData(object)
  object <- RunMCA(object, nmcs = nmcs, features = use.features, slot = slot)
  return(object)
}


#' Step2: Get gene occurrence rate in background and signature genesets
#'
#' @param background.file Background genesets file, in GMT format.
#' @param pathway.file Signature geneset file, in txt fotmat, one gene in one line.
#' @param geneset.name Signature geneset name.
#'
#' @return A data frame include 2 col, colnames is c("background", pathway.name).
#' @export
#'
#' @examples
getGeneRate <- function(background.file = NULL, pathway.file = NULL, pathway.name = NULL) {
  # get background genesets
  if (!file.exists(background.file)) {
    stop(paste0("Cannot find file: ", background.file))
  }
  background_genesets <- readGMT(background.file)

  # get signature geneset
  signature_geneset <- setNames(list(readLines(pathway.file)), geneset.name)
  # merge background and signature genesets
  all_genesets <- c(background_genesets, signature_geneset)

  # get all unique genes from all genesets
  all_gene <- unique(unlist(all_genesets, use.names = FALSE))
  geneset_names <- names(all_genesets)

  # build geneset-gene matrix, row is gene name, col is geneset name
  # Value is whether this gene exist in this geneset, 1-exist 0-noexist
  geneset_gene_matrix <- matrix(0, nrow = length(all_gene), ncol = length(geneset_names),
                          dimnames = list(all_gene, geneset_names))
  for (name in geneset_names) {
    current_list <- all_genesets[[name]]
    for (value in all_gene) {
      if (value %in% current_list) {
        geneset_gene_matrix[value == all_gene, name == geneset_names] <- 1
      }
    }
  }
  background_genesets_df <- data.frame(geneset_gene_matrix)

  # calculate the gene occurrence rate in background and signature genesets
  background_rate <- rowMeans(background_genesets_df)
  signature_rate <- background_genesets_df[, c(geneset.name)]
  gene_rate <- data.frame(background_rate, signature_rate, check.names = FALSE)
  names(gene_rate) <- c("background", geneset.name)

  return (gene_rate)
}


#' Step3: Do regression of gene loading (Y) and gene rate (X)
#'
#' @param object A Seurat object include MCA data in reductions slot.
#' @param gene.rate Gene rate data frame, generated by getGeneRate.
#'
#' @return A data frame include 4 col, include t and p value of background and pathway.
#' @export
#'
#' @examples
doRegression <- function(object, gene.rate = NULL) {
  # get common gene of features and all genes
  common_gene <- intersect(rownames(gene.rate), rownames(object))

  # filter gene of gene rate and loading data
  gene_rate <- gene.rate[common_gene, ]
  mca_loading <- object@reductions$mca@feature.loadings[common_gene, ]

  # do regression by every MCA dimension
  t_rowname <- paste(colnames(gene_rate), "t", sep = ".")
  p_rowname <- paste(colnames(gene_rate), "pvalue", sep = ".")
  rowNames = c(t_rowname, p_rowname)
  regression_result <- matrix(0, nrow = 2 * ncol(gene_rate), ncol = ncol(mca_loading),
                              dimnames = list(rowNames, colnames(mca_loading)))
  for (dim_name in colnames(mca_loading)) {
    # construce data and formula to regression
    mca_dim_loading <- mca_loading[, dim_name]
    lm_data <- data.frame(gene_rate, mca_dim_loading, check.names = FALSE)
    names(lm_data) <- c(names(gene_rate), dim_name)
    formula <- paste(dim_name, "~", paste(names(gene_rate), collapse = " + "))

    lm <- lm(formula, data = lm_data)

    t_value <- summary(lm)$coefficients[-1, 3]
    p_value <- summary(lm)$coefficients[-1, 4]
    regression_result[t_rowname, dim_name] <- t_value
    regression_result[p_rowname, dim_name] <- p_value
  }

  return(regression_result)
}



#' Step4: Compute the pathway activity score.
#'
#' @param object A Seurat object include MCA data in reductions slot.
#' @param regression.data Regression data frame, generated by doRegression.
#'
#' @return A data frame store cell pathway activity score.
#' @export
#'
#' @examples
computeScore <- function(object, regression.data = NULL) {
  pathway_regression_data = regression.data[!grepl("background", rownames(regression.data)), ]
  pathway_regression_data = pathway_regression_data[, 1:20]

  pvalue_rowname = grepl("pvalue", rownames(pathway_regression_data))
  use_dims = colnames(pathway_regression_data)[pathway_regression_data[pvalue_rowname, ] < 0.05]
  use_regression_data = pathway_regression_data[!pvalue_rowname, use_dims]

  mca_embedding <- object@reductions$mca@cell.embeddings
  if (length(use_regression_data) > 0) {
    use_embedding = embeddings[, use_dims]
    for(i in 1:length(use_regression_data)){
      use_embedding[,i] = use_embedding[,i] * use_regression_data[i]
    }
    activity_score = apply(use_embedding, 1, sum) / sum(abs(use_regression_data))
    output = data.frame(barcode = names(activity_score), activity_score = activity_score)
  }

  return(output)
}


readGMT = function(gmt_file_path, n_gene_thre = 0){
  paths = readLines(gmt_file_path)
  genesets = list()
  for(i in 1:length(paths)){
    t = strsplit(paths[i],'\t')[[1]]
    genes = t[3:length(t)]
    genes = genes[which(genes != "")]
    genes = unique(genes)
    genesets[[t[1]]] = genes
  }
  return (genesets)
}

