# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCAStep1 <- function(X) {
    .Call(`_PaaSc_MCAStep1`, X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call(`_PaaSc_MCAStep2`, Z, V, Dc)
}

